/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FindSimilarImagesToUploadedImageRequest,
  FindSimilarItemsRequest,
  GetOffsetOfFileInLoadResultsRequest,
  GetOffsetOfFileInLoadResultsResponse,
  HTTPValidationError,
  LoadAllFilesResponse,
  SearchRequest,
  SearchResponse,
  SearchResultDTO,
} from '../models/index';
import {
    FindSimilarImagesToUploadedImageRequestFromJSON,
    FindSimilarImagesToUploadedImageRequestToJSON,
    FindSimilarItemsRequestFromJSON,
    FindSimilarItemsRequestToJSON,
    GetOffsetOfFileInLoadResultsRequestFromJSON,
    GetOffsetOfFileInLoadResultsRequestToJSON,
    GetOffsetOfFileInLoadResultsResponseFromJSON,
    GetOffsetOfFileInLoadResultsResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LoadAllFilesResponseFromJSON,
    LoadAllFilesResponseToJSON,
    SearchRequestFromJSON,
    SearchRequestToJSON,
    SearchResponseFromJSON,
    SearchResponseToJSON,
    SearchResultDTOFromJSON,
    SearchResultDTOToJSON,
} from '../models/index';

export interface FindItemsWithSimilarDescriptionsFilesFindWithSimilarDescriptionPostRequest {
    xDirectory: string;
    findSimilarItemsRequest: FindSimilarItemsRequest;
}

export interface FindItemsWithSimilarLlmTextFilesFindWithSimilarLlmTextPostRequest {
    xDirectory: string;
    findSimilarItemsRequest: FindSimilarItemsRequest;
}

export interface FindItemsWithSimilarMetadataFilesFindWithSimilarMetadataPostRequest {
    xDirectory: string;
    findSimilarItemsRequest: FindSimilarItemsRequest;
}

export interface FindVisuallySimilarImagesFilesFindVisuallySimilarImagesPostRequest {
    xDirectory: string;
    findSimilarItemsRequest: FindSimilarItemsRequest;
}

export interface FindVisuallySimilarImagesToUploadedImageFilesFindSimilarToUploadedImagePostRequest {
    xDirectory: string;
    findSimilarImagesToUploadedImageRequest: FindSimilarImagesToUploadedImageRequest;
}

export interface FindVisuallySimilarVideosFilesFindVisuallySimilarVideosPostRequest {
    xDirectory: string;
    findSimilarItemsRequest: FindSimilarItemsRequest;
}

export interface GetDirectoryFilesFilesGetRequest {
    xDirectory: string;
    offset?: number;
    limit?: number;
}

export interface GetFileOffsetInLoadResultsFilesGetOffsetInLoadResultsPostRequest {
    xDirectory: string;
    getOffsetOfFileInLoadResultsRequest: GetOffsetOfFileInLoadResultsRequest;
}

export interface SearchFilesSearchPostRequest {
    xDirectory: string;
    searchRequest: SearchRequest;
    offset?: number;
    limit?: number;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     * Find Items With Similar Descriptions
     */
    async findItemsWithSimilarDescriptionsFilesFindWithSimilarDescriptionPostRaw(requestParameters: FindItemsWithSimilarDescriptionsFilesFindWithSimilarDescriptionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResultDTO>>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling findItemsWithSimilarDescriptionsFilesFindWithSimilarDescriptionPost().'
            );
        }

        if (requestParameters['findSimilarItemsRequest'] == null) {
            throw new runtime.RequiredError(
                'findSimilarItemsRequest',
                'Required parameter "findSimilarItemsRequest" was null or undefined when calling findItemsWithSimilarDescriptionsFilesFindWithSimilarDescriptionPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/find-with-similar-description`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindSimilarItemsRequestToJSON(requestParameters['findSimilarItemsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultDTOFromJSON));
    }

    /**
     * Find Items With Similar Descriptions
     */
    async findItemsWithSimilarDescriptionsFilesFindWithSimilarDescriptionPost(requestParameters: FindItemsWithSimilarDescriptionsFilesFindWithSimilarDescriptionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResultDTO>> {
        const response = await this.findItemsWithSimilarDescriptionsFilesFindWithSimilarDescriptionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Items With Similar Llm Text
     */
    async findItemsWithSimilarLlmTextFilesFindWithSimilarLlmTextPostRaw(requestParameters: FindItemsWithSimilarLlmTextFilesFindWithSimilarLlmTextPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResultDTO>>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling findItemsWithSimilarLlmTextFilesFindWithSimilarLlmTextPost().'
            );
        }

        if (requestParameters['findSimilarItemsRequest'] == null) {
            throw new runtime.RequiredError(
                'findSimilarItemsRequest',
                'Required parameter "findSimilarItemsRequest" was null or undefined when calling findItemsWithSimilarLlmTextFilesFindWithSimilarLlmTextPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/find-with-similar-llm-text`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindSimilarItemsRequestToJSON(requestParameters['findSimilarItemsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultDTOFromJSON));
    }

    /**
     * Find Items With Similar Llm Text
     */
    async findItemsWithSimilarLlmTextFilesFindWithSimilarLlmTextPost(requestParameters: FindItemsWithSimilarLlmTextFilesFindWithSimilarLlmTextPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResultDTO>> {
        const response = await this.findItemsWithSimilarLlmTextFilesFindWithSimilarLlmTextPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Items With Similar Metadata
     */
    async findItemsWithSimilarMetadataFilesFindWithSimilarMetadataPostRaw(requestParameters: FindItemsWithSimilarMetadataFilesFindWithSimilarMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResultDTO>>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling findItemsWithSimilarMetadataFilesFindWithSimilarMetadataPost().'
            );
        }

        if (requestParameters['findSimilarItemsRequest'] == null) {
            throw new runtime.RequiredError(
                'findSimilarItemsRequest',
                'Required parameter "findSimilarItemsRequest" was null or undefined when calling findItemsWithSimilarMetadataFilesFindWithSimilarMetadataPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/find-with-similar-metadata`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindSimilarItemsRequestToJSON(requestParameters['findSimilarItemsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultDTOFromJSON));
    }

    /**
     * Find Items With Similar Metadata
     */
    async findItemsWithSimilarMetadataFilesFindWithSimilarMetadataPost(requestParameters: FindItemsWithSimilarMetadataFilesFindWithSimilarMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResultDTO>> {
        const response = await this.findItemsWithSimilarMetadataFilesFindWithSimilarMetadataPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Visually Similar Images
     */
    async findVisuallySimilarImagesFilesFindVisuallySimilarImagesPostRaw(requestParameters: FindVisuallySimilarImagesFilesFindVisuallySimilarImagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResultDTO>>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling findVisuallySimilarImagesFilesFindVisuallySimilarImagesPost().'
            );
        }

        if (requestParameters['findSimilarItemsRequest'] == null) {
            throw new runtime.RequiredError(
                'findSimilarItemsRequest',
                'Required parameter "findSimilarItemsRequest" was null or undefined when calling findVisuallySimilarImagesFilesFindVisuallySimilarImagesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/find-visually-similar-images`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindSimilarItemsRequestToJSON(requestParameters['findSimilarItemsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultDTOFromJSON));
    }

    /**
     * Find Visually Similar Images
     */
    async findVisuallySimilarImagesFilesFindVisuallySimilarImagesPost(requestParameters: FindVisuallySimilarImagesFilesFindVisuallySimilarImagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResultDTO>> {
        const response = await this.findVisuallySimilarImagesFilesFindVisuallySimilarImagesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Visually Similar Images To Uploaded Image
     */
    async findVisuallySimilarImagesToUploadedImageFilesFindSimilarToUploadedImagePostRaw(requestParameters: FindVisuallySimilarImagesToUploadedImageFilesFindSimilarToUploadedImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResultDTO>>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling findVisuallySimilarImagesToUploadedImageFilesFindSimilarToUploadedImagePost().'
            );
        }

        if (requestParameters['findSimilarImagesToUploadedImageRequest'] == null) {
            throw new runtime.RequiredError(
                'findSimilarImagesToUploadedImageRequest',
                'Required parameter "findSimilarImagesToUploadedImageRequest" was null or undefined when calling findVisuallySimilarImagesToUploadedImageFilesFindSimilarToUploadedImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/find-similar-to-uploaded-image`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindSimilarImagesToUploadedImageRequestToJSON(requestParameters['findSimilarImagesToUploadedImageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultDTOFromJSON));
    }

    /**
     * Find Visually Similar Images To Uploaded Image
     */
    async findVisuallySimilarImagesToUploadedImageFilesFindSimilarToUploadedImagePost(requestParameters: FindVisuallySimilarImagesToUploadedImageFilesFindSimilarToUploadedImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResultDTO>> {
        const response = await this.findVisuallySimilarImagesToUploadedImageFilesFindSimilarToUploadedImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Visually Similar Videos
     */
    async findVisuallySimilarVideosFilesFindVisuallySimilarVideosPostRaw(requestParameters: FindVisuallySimilarVideosFilesFindVisuallySimilarVideosPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResultDTO>>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling findVisuallySimilarVideosFilesFindVisuallySimilarVideosPost().'
            );
        }

        if (requestParameters['findSimilarItemsRequest'] == null) {
            throw new runtime.RequiredError(
                'findSimilarItemsRequest',
                'Required parameter "findSimilarItemsRequest" was null or undefined when calling findVisuallySimilarVideosFilesFindVisuallySimilarVideosPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/find-visually-similar-videos`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindSimilarItemsRequestToJSON(requestParameters['findSimilarItemsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultDTOFromJSON));
    }

    /**
     * Find Visually Similar Videos
     */
    async findVisuallySimilarVideosFilesFindVisuallySimilarVideosPost(requestParameters: FindVisuallySimilarVideosFilesFindVisuallySimilarVideosPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResultDTO>> {
        const response = await this.findVisuallySimilarVideosFilesFindVisuallySimilarVideosPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Directory Files
     */
    async getDirectoryFilesFilesGetRaw(requestParameters: GetDirectoryFilesFilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoadAllFilesResponse>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling getDirectoryFilesFilesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoadAllFilesResponseFromJSON(jsonValue));
    }

    /**
     * Get Directory Files
     */
    async getDirectoryFilesFilesGet(requestParameters: GetDirectoryFilesFilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoadAllFilesResponse> {
        const response = await this.getDirectoryFilesFilesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get File Offset In Load Results
     */
    async getFileOffsetInLoadResultsFilesGetOffsetInLoadResultsPostRaw(requestParameters: GetFileOffsetInLoadResultsFilesGetOffsetInLoadResultsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOffsetOfFileInLoadResultsResponse>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling getFileOffsetInLoadResultsFilesGetOffsetInLoadResultsPost().'
            );
        }

        if (requestParameters['getOffsetOfFileInLoadResultsRequest'] == null) {
            throw new runtime.RequiredError(
                'getOffsetOfFileInLoadResultsRequest',
                'Required parameter "getOffsetOfFileInLoadResultsRequest" was null or undefined when calling getFileOffsetInLoadResultsFilesGetOffsetInLoadResultsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/get-offset-in-load-results`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetOffsetOfFileInLoadResultsRequestToJSON(requestParameters['getOffsetOfFileInLoadResultsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOffsetOfFileInLoadResultsResponseFromJSON(jsonValue));
    }

    /**
     * Get File Offset In Load Results
     */
    async getFileOffsetInLoadResultsFilesGetOffsetInLoadResultsPost(requestParameters: GetFileOffsetInLoadResultsFilesGetOffsetInLoadResultsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOffsetOfFileInLoadResultsResponse> {
        const response = await this.getFileOffsetInLoadResultsFilesGetOffsetInLoadResultsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search
     */
    async searchFilesSearchPostRaw(requestParameters: SearchFilesSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponse>> {
        if (requestParameters['xDirectory'] == null) {
            throw new runtime.RequiredError(
                'xDirectory',
                'Required parameter "xDirectory" was null or undefined when calling searchFilesSearchPost().'
            );
        }

        if (requestParameters['searchRequest'] == null) {
            throw new runtime.RequiredError(
                'searchRequest',
                'Required parameter "searchRequest" was null or undefined when calling searchFilesSearchPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDirectory'] != null) {
            headerParameters['x-directory'] = String(requestParameters['xDirectory']);
        }

        const response = await this.request({
            path: `/files/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchRequestToJSON(requestParameters['searchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseFromJSON(jsonValue));
    }

    /**
     * Search
     */
    async searchFilesSearchPost(requestParameters: SearchFilesSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponse> {
        const response = await this.searchFilesSearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
