/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DirectoryMetadataResponse
 */
export interface DirectoryMetadataResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DirectoryMetadataResponse
     */
    hasLlmDescriptions: boolean;
}

/**
 * Check if a given object implements the DirectoryMetadataResponse interface.
 */
export function instanceOfDirectoryMetadataResponse(value: object): value is DirectoryMetadataResponse {
    if (!('hasLlmDescriptions' in value) || value['hasLlmDescriptions'] === undefined) return false;
    return true;
}

export function DirectoryMetadataResponseFromJSON(json: any): DirectoryMetadataResponse {
    return DirectoryMetadataResponseFromJSONTyped(json, false);
}

export function DirectoryMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectoryMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasLlmDescriptions': json['has_llm_descriptions'],
    };
}

export function DirectoryMetadataResponseToJSON(value?: DirectoryMetadataResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_llm_descriptions': value['hasLlmDescriptions'],
    };
}

