/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileType } from './FileType';
import {
    FileTypeFromJSON,
    FileTypeFromJSONTyped,
    FileTypeToJSON,
} from './FileType';

/**
 * 
 * @export
 * @interface FileMetadataDTO
 */
export interface FileMetadataDTO {
    /**
     * 
     * @type {number}
     * @memberof FileMetadataDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDTO
     */
    addedAt: string;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDTO
     */
    description: string;
    /**
     * 
     * @type {FileType}
     * @memberof FileMetadataDTO
     */
    fileType: FileType;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDTO
     */
    thumbnailBase64: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileMetadataDTO
     */
    isScreenshot: boolean;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDTO
     */
    ocrText: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDTO
     */
    transcript: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FileMetadataDTO
     */
    isTranscriptFixed: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDTO
     */
    llmDescription: string | null;
}



/**
 * Check if a given object implements the FileMetadataDTO interface.
 */
export function instanceOfFileMetadataDTO(value: object): value is FileMetadataDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('addedAt' in value) || value['addedAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    if (!('thumbnailBase64' in value) || value['thumbnailBase64'] === undefined) return false;
    if (!('isScreenshot' in value) || value['isScreenshot'] === undefined) return false;
    if (!('ocrText' in value) || value['ocrText'] === undefined) return false;
    if (!('transcript' in value) || value['transcript'] === undefined) return false;
    if (!('isTranscriptFixed' in value) || value['isTranscriptFixed'] === undefined) return false;
    if (!('llmDescription' in value) || value['llmDescription'] === undefined) return false;
    return true;
}

export function FileMetadataDTOFromJSON(json: any): FileMetadataDTO {
    return FileMetadataDTOFromJSONTyped(json, false);
}

export function FileMetadataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMetadataDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'addedAt': json['added_at'],
        'description': json['description'],
        'fileType': FileTypeFromJSON(json['file_type']),
        'thumbnailBase64': json['thumbnail_base64'],
        'isScreenshot': json['is_screenshot'],
        'ocrText': json['ocr_text'],
        'transcript': json['transcript'],
        'isTranscriptFixed': json['is_transcript_fixed'],
        'llmDescription': json['llm_description'],
    };
}

export function FileMetadataDTOToJSON(value?: FileMetadataDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'added_at': value['addedAt'],
        'description': value['description'],
        'file_type': FileTypeToJSON(value['fileType']),
        'thumbnail_base64': value['thumbnailBase64'],
        'is_screenshot': value['isScreenshot'],
        'ocr_text': value['ocrText'],
        'transcript': value['transcript'],
        'is_transcript_fixed': value['isTranscriptFixed'],
        'llm_description': value['llmDescription'],
    };
}

