/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindSimilarImagesToUploadedImageRequest
 */
export interface FindSimilarImagesToUploadedImageRequest {
    /**
     * 
     * @type {string}
     * @memberof FindSimilarImagesToUploadedImageRequest
     */
    imageDataBase64: string;
}

/**
 * Check if a given object implements the FindSimilarImagesToUploadedImageRequest interface.
 */
export function instanceOfFindSimilarImagesToUploadedImageRequest(value: object): value is FindSimilarImagesToUploadedImageRequest {
    if (!('imageDataBase64' in value) || value['imageDataBase64'] === undefined) return false;
    return true;
}

export function FindSimilarImagesToUploadedImageRequestFromJSON(json: any): FindSimilarImagesToUploadedImageRequest {
    return FindSimilarImagesToUploadedImageRequestFromJSONTyped(json, false);
}

export function FindSimilarImagesToUploadedImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindSimilarImagesToUploadedImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'imageDataBase64': json['image_data_base64'],
    };
}

export function FindSimilarImagesToUploadedImageRequestToJSON(value?: FindSimilarImagesToUploadedImageRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'image_data_base64': value['imageDataBase64'],
    };
}

