/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindSimilarItemsRequest
 */
export interface FindSimilarItemsRequest {
    /**
     * 
     * @type {number}
     * @memberof FindSimilarItemsRequest
     */
    fileId: number;
}

/**
 * Check if a given object implements the FindSimilarItemsRequest interface.
 */
export function instanceOfFindSimilarItemsRequest(value: object): value is FindSimilarItemsRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function FindSimilarItemsRequestFromJSON(json: any): FindSimilarItemsRequest {
    return FindSimilarItemsRequestFromJSONTyped(json, false);
}

export function FindSimilarItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindSimilarItemsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
    };
}

export function FindSimilarItemsRequestToJSON(value?: FindSimilarItemsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_id': value['fileId'],
    };
}

