/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOffsetOfFileInLoadResultsRequest
 */
export interface GetOffsetOfFileInLoadResultsRequest {
    /**
     * 
     * @type {number}
     * @memberof GetOffsetOfFileInLoadResultsRequest
     */
    fileId: number;
}

/**
 * Check if a given object implements the GetOffsetOfFileInLoadResultsRequest interface.
 */
export function instanceOfGetOffsetOfFileInLoadResultsRequest(value: object): value is GetOffsetOfFileInLoadResultsRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function GetOffsetOfFileInLoadResultsRequestFromJSON(json: any): GetOffsetOfFileInLoadResultsRequest {
    return GetOffsetOfFileInLoadResultsRequestFromJSONTyped(json, false);
}

export function GetOffsetOfFileInLoadResultsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOffsetOfFileInLoadResultsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
    };
}

export function GetOffsetOfFileInLoadResultsRequestToJSON(value?: GetOffsetOfFileInLoadResultsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_id': value['fileId'],
    };
}

