/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOffsetOfFileInLoadResultsResponse
 */
export interface GetOffsetOfFileInLoadResultsResponse {
    /**
     * 
     * @type {number}
     * @memberof GetOffsetOfFileInLoadResultsResponse
     */
    idx: number;
}

/**
 * Check if a given object implements the GetOffsetOfFileInLoadResultsResponse interface.
 */
export function instanceOfGetOffsetOfFileInLoadResultsResponse(value: object): value is GetOffsetOfFileInLoadResultsResponse {
    if (!('idx' in value) || value['idx'] === undefined) return false;
    return true;
}

export function GetOffsetOfFileInLoadResultsResponseFromJSON(json: any): GetOffsetOfFileInLoadResultsResponse {
    return GetOffsetOfFileInLoadResultsResponseFromJSONTyped(json, false);
}

export function GetOffsetOfFileInLoadResultsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOffsetOfFileInLoadResultsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'idx': json['idx'],
    };
}

export function GetOffsetOfFileInLoadResultsResponseToJSON(value?: GetOffsetOfFileInLoadResultsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idx': value['idx'],
    };
}

