/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenFileRequest
 */
export interface OpenFileRequest {
    /**
     * 
     * @type {number}
     * @memberof OpenFileRequest
     */
    fileId: number;
}

/**
 * Check if a given object implements the OpenFileRequest interface.
 */
export function instanceOfOpenFileRequest(value: object): value is OpenFileRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OpenFileRequestFromJSON(json: any): OpenFileRequest {
    return OpenFileRequestFromJSONTyped(json, false);
}

export function OpenFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
    };
}

export function OpenFileRequestToJSON(value?: OpenFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_id': value['fileId'],
    };
}

