/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisteredDirectoryDTO
 */
export interface RegisteredDirectoryDTO {
    /**
     * 
     * @type {string}
     * @memberof RegisteredDirectoryDTO
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredDirectoryDTO
     */
    ready: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredDirectoryDTO
     */
    failed: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisteredDirectoryDTO
     */
    initProgressDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof RegisteredDirectoryDTO
     */
    initProgress?: number;
}

/**
 * Check if a given object implements the RegisteredDirectoryDTO interface.
 */
export function instanceOfRegisteredDirectoryDTO(value: object): value is RegisteredDirectoryDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ready' in value) || value['ready'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    return true;
}

export function RegisteredDirectoryDTOFromJSON(json: any): RegisteredDirectoryDTO {
    return RegisteredDirectoryDTOFromJSONTyped(json, false);
}

export function RegisteredDirectoryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisteredDirectoryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ready': json['ready'],
        'failed': json['failed'],
        'initProgressDescription': json['init_progress_description'] == null ? undefined : json['init_progress_description'],
        'initProgress': json['init_progress'] == null ? undefined : json['init_progress'],
    };
}

export function RegisteredDirectoryDTOToJSON(value?: RegisteredDirectoryDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'ready': value['ready'],
        'failed': value['failed'],
        'init_progress_description': value['initProgressDescription'],
        'init_progress': value['initProgress'],
    };
}

