/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResultDTO } from './SearchResultDTO';
import {
    SearchResultDTOFromJSON,
    SearchResultDTOFromJSONTyped,
    SearchResultDTOToJSON,
} from './SearchResultDTO';

/**
 * 
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * 
     * @type {number}
     * @memberof SearchResponse
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof SearchResponse
     */
    total: number;
    /**
     * 
     * @type {Array<SearchResultDTO>}
     * @memberof SearchResponse
     */
    results: Array<SearchResultDTO>;
}

/**
 * Check if a given object implements the SearchResponse interface.
 */
export function instanceOfSearchResponse(value: object): value is SearchResponse {
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function SearchResponseFromJSON(json: any): SearchResponse {
    return SearchResponseFromJSONTyped(json, false);
}

export function SearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'],
        'total': json['total'],
        'results': ((json['results'] as Array<any>).map(SearchResultDTOFromJSON)),
    };
}

export function SearchResponseToJSON(value?: SearchResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'offset': value['offset'],
        'total': value['total'],
        'results': ((value['results'] as Array<any>).map(SearchResultDTOToJSON)),
    };
}

