/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectDirectoryResponse
 */
export interface SelectDirectoryResponse {
    /**
     * 
     * @type {string}
     * @memberof SelectDirectoryResponse
     */
    selectedPath: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SelectDirectoryResponse
     */
    canceled: boolean;
}

/**
 * Check if a given object implements the SelectDirectoryResponse interface.
 */
export function instanceOfSelectDirectoryResponse(value: object): value is SelectDirectoryResponse {
    if (!('selectedPath' in value) || value['selectedPath'] === undefined) return false;
    if (!('canceled' in value) || value['canceled'] === undefined) return false;
    return true;
}

export function SelectDirectoryResponseFromJSON(json: any): SelectDirectoryResponse {
    return SelectDirectoryResponseFromJSONTyped(json, false);
}

export function SelectDirectoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectDirectoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'selectedPath': json['selected_path'],
        'canceled': json['canceled'],
    };
}

export function SelectDirectoryResponseToJSON(value?: SelectDirectoryResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'selected_path': value['selectedPath'],
        'canceled': value['canceled'],
    };
}

