/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnregisterDirectoryRequest
 */
export interface UnregisterDirectoryRequest {
    /**
     * 
     * @type {string}
     * @memberof UnregisterDirectoryRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UnregisterDirectoryRequest interface.
 */
export function instanceOfUnregisterDirectoryRequest(value: object): value is UnregisterDirectoryRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UnregisterDirectoryRequestFromJSON(json: any): UnregisterDirectoryRequest {
    return UnregisterDirectoryRequestFromJSONTyped(json, false);
}

export function UnregisterDirectoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnregisterDirectoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UnregisterDirectoryRequestToJSON(value?: UnregisterDirectoryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

