/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateScreenshotTypeRequest
 */
export interface UpdateScreenshotTypeRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateScreenshotTypeRequest
     */
    fileId: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateScreenshotTypeRequest
     */
    isScreenshot: boolean;
}

/**
 * Check if a given object implements the UpdateScreenshotTypeRequest interface.
 */
export function instanceOfUpdateScreenshotTypeRequest(value: object): value is UpdateScreenshotTypeRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('isScreenshot' in value) || value['isScreenshot'] === undefined) return false;
    return true;
}

export function UpdateScreenshotTypeRequestFromJSON(json: any): UpdateScreenshotTypeRequest {
    return UpdateScreenshotTypeRequestFromJSONTyped(json, false);
}

export function UpdateScreenshotTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateScreenshotTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
        'isScreenshot': json['is_screenshot'],
    };
}

export function UpdateScreenshotTypeRequestToJSON(value?: UpdateScreenshotTypeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_id': value['fileId'],
        'is_screenshot': value['isScreenshot'],
    };
}

