/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTranscriptRequest
 */
export interface UpdateTranscriptRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateTranscriptRequest
     */
    fileId: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTranscriptRequest
     */
    transcript: string;
}

/**
 * Check if a given object implements the UpdateTranscriptRequest interface.
 */
export function instanceOfUpdateTranscriptRequest(value: object): value is UpdateTranscriptRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('transcript' in value) || value['transcript'] === undefined) return false;
    return true;
}

export function UpdateTranscriptRequestFromJSON(json: any): UpdateTranscriptRequest {
    return UpdateTranscriptRequestFromJSONTyped(json, false);
}

export function UpdateTranscriptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTranscriptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
        'transcript': json['transcript'],
    };
}

export function UpdateTranscriptRequestToJSON(value?: UpdateTranscriptRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_id': value['fileId'],
        'transcript': value['transcript'],
    };
}

