/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDescriptionRequest
 */
export interface UpdateDescriptionRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateDescriptionRequest
     */
    fileId: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateDescriptionRequest
     */
    description: string;
}

/**
 * Check if a given object implements the UpdateDescriptionRequest interface.
 */
export function instanceOfUpdateDescriptionRequest(value: object): value is UpdateDescriptionRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function UpdateDescriptionRequestFromJSON(json: any): UpdateDescriptionRequest {
    return UpdateDescriptionRequestFromJSONTyped(json, false);
}

export function UpdateDescriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDescriptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
        'description': json['description'],
    };
}

export function UpdateDescriptionRequestToJSON(value?: UpdateDescriptionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_id': value['fileId'],
        'description': value['description'],
    };
}

