/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOCRTextRequest
 */
export interface UpdateOCRTextRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateOCRTextRequest
     */
    fileId: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateOCRTextRequest
     */
    ocrText: string;
}

/**
 * Check if a given object implements the UpdateOCRTextRequest interface.
 */
export function instanceOfUpdateOCRTextRequest(value: object): value is UpdateOCRTextRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('ocrText' in value) || value['ocrText'] === undefined) return false;
    return true;
}

export function UpdateOCRTextRequestFromJSON(json: any): UpdateOCRTextRequest {
    return UpdateOCRTextRequestFromJSONTyped(json, false);
}

export function UpdateOCRTextRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOCRTextRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
        'ocrText': json['ocr_text'],
    };
}

export function UpdateOCRTextRequestToJSON(value?: UpdateOCRTextRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_id': value['fileId'],
        'ocr_text': value['ocrText'],
    };
}

